from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

AUTO = Button(area=(1200, 543, 1240, 568), color=(168, 218, 249), button=(1200, 543, 1240, 568), file="./assets/train/AUTO.png")
CANCEL = Button(area=(921, 591, 973, 618), color=(174, 177, 181), button=(921, 591, 973, 618), file="./assets/train/CANCEL.png")
CHANGE = Button(area=(1085, 598, 1142, 628), color=(133, 157, 207), button=(1085, 598, 1142, 628), file="./assets/train/CHANGE.png")
END = Button(area=(1036, 639, 1121, 670), color=(103, 147, 223), button=(1036, 639, 1121, 670), file="./assets/train/END.png")
EZ_BUTTON = Button(area=(855, 267, 1074, 316), color=(154, 199, 134), button=(855, 267, 1074, 316), file="./assets/train/EZ_BUTTON.png")
GO_BUTTON = Button(area=(1006, 579, 1222, 647), color=(118, 165, 224), button=(1006, 579, 1222, 647), file="./assets/train/GO_BUTTON.png")
HURY_ADD = Button(area=(58, 21, 135, 45), color=(137, 148, 167), button=(58, 21, 135, 45), file="./assets/train/HURY_ADD.png")
MENU = Button(area=(1181, 24, 1221, 46), color=(189, 191, 197), button=(1181, 24, 1221, 46), file="./assets/train/MENU.png")
REPORT = Button(area=(1093, 38, 1182, 68), color=(203, 204, 208), button=(1093, 38, 1182, 68), file="./assets/train/REPORT.png")
SETTINGS = Button(area=(952, 143, 975, 168), color=(243, 241, 243), button=(952, 143, 975, 168), file="./assets/train/SETTINGS.png")
TEAM = Button(area=(1196, 105, 1239, 136), color=(192, 212, 252), button=(1196, 105, 1239, 136), file="./assets/train/TEAM.png")
WULI_TEST = Button(area=(636, 188, 1207, 301), color=(215, 210, 207), button=(636, 188, 1207, 301), file="./assets/train/WULI_TEST.png")
