from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

公会战BOSS_1 = Button(area=(459, 200, 517, 225), color=(204, 205, 210), button=(459, 200, 517, 225), file="./assets/ghz/公会战BOSS_1.png")
公会战BOSS_1_选中 = Button(area=(446, 201, 457, 220), color=(71, 126, 219), button=(446, 201, 457, 220), file="./assets/ghz/公会战BOSS_1_选中.png")
公会战BOSS_2 = Button(area=(562, 200, 620, 225), color=(200, 201, 206), button=(562, 200, 620, 225), file="./assets/ghz/公会战BOSS_2.png")
公会战BOSS_2_选中 = Button(area=(549, 202, 558, 219), color=(70, 125, 219), button=(549, 202, 558, 219), file="./assets/ghz/公会战BOSS_2_选中.png")
公会战BOSS_3 = Button(area=(667, 201, 725, 225), color=(198, 199, 204), button=(667, 201, 725, 225), file="./assets/ghz/公会战BOSS_3.png")
公会战BOSS_3_选中 = Button(area=(651, 205, 662, 222), color=(67, 120, 217), button=(651, 205, 662, 222), file="./assets/ghz/公会战BOSS_3_选中.png")
公会战BOSS_4 = Button(area=(768, 202, 829, 223), color=(193, 194, 199), button=(768, 202, 829, 223), file="./assets/ghz/公会战BOSS_4.png")
公会战BOSS_4_选中 = Button(area=(755, 204, 765, 222), color=(68, 121, 217), button=(755, 204, 765, 222), file="./assets/ghz/公会战BOSS_4_选中.png")
公会战BOSS_5 = Button(area=(867, 202, 934, 226), color=(204, 205, 209), button=(867, 202, 934, 226), file="./assets/ghz/公会战BOSS_5.png")
公会战BOSS_5_选中 = Button(area=(859, 208, 865, 224), color=(65, 116, 216), button=(859, 208, 865, 224), file="./assets/ghz/公会战BOSS_5_选中.png")
第四阶段 = Button(area=(688, 513, 758, 533), color=(222, 128, 133), button=(688, 513, 758, 533), file="./assets/ghz/第四阶段.png")
训练模式 = Button(area=(581, 42, 700, 72), color=(127, 149, 201), button=(581, 42, 700, 72), file="./assets/ghz/训练模式.png")
