from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

BATTLE_START = Button(area=(1079, 588, 1189, 619), color=(122, 154, 211), button=(1079, 588, 1189, 619), file="./assets/character/BATTLE_START.png")
DOCK_SCROLL = Button(area=(1218, 165, 1230, 484), color=(22, 30, 42), button=(1218, 165, 1230, 484), file="./assets/character/DOCK_SCROLL.png")
NULL_FIVE = Button(area=(71, 549, 183, 661), color=(239, 236, 239), button=(71, 549, 183, 661), file="./assets/character/NULL_FIVE.png")
NULL_FOUR = Button(area=(218, 547, 330, 664), color=(239, 236, 239), button=(218, 547, 330, 664), file="./assets/character/NULL_FOUR.png")
NULL_MORE = Button(area=(72, 546, 772, 664), color=(188, 186, 188), button=(72, 546, 772, 664), file="./assets/character/NULL_MORE.png")
NULL_ONE = Button(area=(658, 552, 768, 661), color=(239, 236, 239), button=(658, 552, 768, 661), file="./assets/character/NULL_ONE.png")
NULL_THREE = Button(area=(364, 547, 474, 665), color=(239, 236, 239), button=(364, 547, 474, 665), file="./assets/character/NULL_THREE.png")
NULL_TWO = Button(area=(511, 550, 623, 659), color=(239, 236, 239), button=(511, 550, 623, 659), file="./assets/character/NULL_TWO.png")
SCROLL = Button(area=(1218, 178, 1230, 201), color=(102, 149, 224), button=(1218, 178, 1230, 201), file="./assets/character/SCROLL.png")
TEMPLATE_CHUNJIAN = Template(file="./assets/character/TEMPLATE_CHUNJIAN.png")
TEMPLATE_QINGBING = Template(file="./assets/character/TEMPLATE_QINGBING.png")
TEMPLATE_SHUIMA = Template(file="./assets/character/TEMPLATE_SHUIMA.png")
TEMPLATE_SHUISHENGMU = Template(file="./assets/character/TEMPLATE_SHUISHENGMU.png")
TEMPLATE_TIANJIE = Template(file="./assets/character/TEMPLATE_TIANJIE.png")
TEMPLATE_UE = Template(file="./assets/character/TEMPLATE_UE.png")
