from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

ADVENTURE = Button(area=(694, 689, 740, 715), color=(199, 203, 219), button=(694, 689, 740, 715), file="./assets/ui/ADVENTURE.png")
GO_TO_MAIN = Button(area=(67, 690, 154, 714), color=(200, 201, 218), button=(67, 690, 154, 714), file="./assets/ui/GO_TO_MAIN.png")
GO_TO_MENU = Button(area=(1138, 692, 1199, 713), color=(196, 201, 223), button=(1138, 692, 1199, 713), file="./assets/ui/GO_TO_MENU.png")
GO_TO_ROLE = Button(area=(231, 687, 283, 716), color=(189, 187, 193), button=(231, 687, 283, 716), file="./assets/ui/GO_TO_ROLE.png")
MAIN_CHECK = Button(area=(897, 33, 940, 78), color=(195, 212, 243), button=(897, 33, 940, 78), file="./assets/ui/MAIN_CHECK.png")
MAIN_CHECK_2 = Button(area=(974, 38, 1020, 76), color=(181, 203, 246), button=(974, 38, 1020, 76), file="./assets/ui/MAIN_CHECK_2.png")
MENU_CHECK = Button(area=(154, 433, 309, 459), color=(184, 186, 191), button=(154, 433, 309, 459), file="./assets/ui/MENU_CHECK.png")
TEAM_BATTLE = Button(area=(1133, 419, 1209, 448), color=(180, 197, 212), button=(1133, 419, 1209, 448), file="./assets/ui/TEAM_BATTLE.png")
TEAM_BATTLE_CHECK = Button(area=(589, 526, 715, 554), color=(131, 176, 251), button=(589, 526, 715, 554), file="./assets/ui/TEAM_BATTLE_CHECK.png")
TRAIN_CHECK = Button(area=(656, 203, 767, 278), color=(163, 145, 116), button=(656, 203, 767, 278), file="./assets/ui/TRAIN_CHECK.png")
主界面检查 = Button(area=(1203, 37, 1245, 77), color=(221, 229, 248), button=(1203, 37, 1245, 77), file="./assets/ui/主界面检查.png")
前往角色界面 = Button(area=(231, 689, 278, 717), color=(191, 190, 200), button=(231, 689, 278, 717), file="./assets/ui/前往角色界面.png")
