"""
将 assets/icons/unit_cropped/ 中的图标迁移为 TEMPLATE 格式。

操作步骤：
  1. 删除 assets/character/TEMPLATE_*.png（旧模板）
  2. 将 unit_cropped/{uid}.png 复制到 assets/character/TEMPLATE_{file_name}.png
     文件名使用 unit_names.json 中 uid 对应的中文名（空格→_, ★→S）
     例：106911 → "霸瞳 ★1" → TEMPLATE_霸瞳_S1.png
  3. 重写 module/character/assets.py：
     - 保留原有 Button 定义（BATTLE_START、NULL_* 等）
     - 新增 UNIT_NAMES dict（uid → 中文名含星级）
     - 添加 TEMPLATE_{var_name} 定义
       变量名：★ → S，空格 → _（★ 不是合法 Python 标识符）
       例：TEMPLATE_霸瞳_S1

Usage:
    python dev_tools/build_character_assets.py
"""

import json
import os
import shutil

ICONS_CROPPED = "./assets/icons/unit_cropped"
CHAR_DIR      = "./assets/character"
NAMES_FILE    = "./assets/icons/unit_names.json"
ASSETS_PY     = "./module/character/assets.py"

ASSETS_HEADER = """\
from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/build_character_assets.py.
# Don't modify it manually.

BATTLE_START = Button(area=(1079, 588, 1189, 619), color=(122, 154, 211), button=(1079, 588, 1189, 619), file="./assets/character/BATTLE_START.png")
DOCK_SCROLL = Button(area=(1218, 165, 1230, 484), color=(22, 30, 42), button=(1218, 165, 1230, 484), file="./assets/character/DOCK_SCROLL.png")
NULL_FIVE = Button(area=(71, 549, 183, 661), color=(239, 236, 239), button=(71, 549, 183, 661), file="./assets/character/NULL_FIVE.png")
NULL_FOUR = Button(area=(218, 547, 330, 664), color=(239, 236, 239), button=(218, 547, 330, 664), file="./assets/character/NULL_FOUR.png")
NULL_MORE = Button(area=(72, 546, 772, 664), color=(188, 186, 188), button=(72, 546, 772, 664), file="./assets/character/NULL_MORE.png")
NULL_ONE = Button(area=(658, 552, 768, 661), color=(239, 236, 239), button=(658, 552, 768, 661), file="./assets/character/NULL_ONE.png")
NULL_THREE = Button(area=(364, 547, 474, 665), color=(239, 236, 239), button=(364, 547, 474, 665), file="./assets/character/NULL_THREE.png")
NULL_TWO = Button(area=(511, 550, 623, 659), color=(239, 236, 239), button=(511, 550, 623, 659), file="./assets/character/NULL_TWO.png")
SCROLL = Button(area=(1218, 178, 1230, 201), color=(102, 149, 224), button=(1218, 178, 1230, 201), file="./assets/character/SCROLL.png")
"""


def name_to_filename(display_name: str) -> str:
    """中文名 → 文件名（空格换成_，★ 改为S，与变量名保持一致）
    例："霸瞳 ★1" → "霸瞳_S1"
    """
    return display_name.replace(" ", "_").replace("★", "S")


def name_to_varname(display_name: str) -> str:
    """中文名 → Python 变量名。
    规则：★→S，其余非字母/数字/中文字符均替换为 _，并合并连续下划线。
    例："霸瞳 ★1"       → "霸瞳_S1"
        "多洛西(万圣) ★1" → "多洛西_万圣_S1"
    """
    import re
    s = display_name.replace("★", "S")
    # 把所有不是字母、数字、中文、下划线的字符替换为 _
    s = re.sub(r"[^\w\u4e00-\u9fff]", "_", s)
    # 合并连续下划线，去掉首尾下划线
    s = re.sub(r"_+", "_", s).strip("_")
    return s


def main():
    with open(NAMES_FILE, encoding="utf-8") as f:
        names: dict[str, str] = json.load(f)

    # 只保留 ★1/★3/★6，按 UID 排序
    valid_uids = sorted(
        uid for uid in names
        if uid.endswith("11") or uid.endswith("31") or uid.endswith("61")
    )
    print(f"有效 UID 数量（★1/★3/★6）: {len(valid_uids)}")

    # ── 1. 删除旧 TEMPLATE_*.png ──────────────────────────────────────────────
    deleted = 0
    for fn in os.listdir(CHAR_DIR):
        if fn.startswith("TEMPLATE_") and fn.endswith(".png"):
            os.remove(os.path.join(CHAR_DIR, fn))
            deleted += 1
    print(f"已删除旧模板: {deleted} 个")

    # ── 2. 复制新模板（按中文名命名）────────────────────────────────────────────
    copied = missing = 0
    # uid → (filename, varname) 映射，供 assets.py 生成使用
    uid_map: dict[str, tuple[str, str]] = {}

    for uid in valid_uids:
        src = os.path.join(ICONS_CROPPED, f"{uid}.png")
        if not os.path.exists(src):
            print(f"  跳过（源文件不存在）: {src}")
            missing += 1
            continue

        display = names[uid]
        fname   = f"TEMPLATE_{name_to_filename(display)}.png"
        varname = f"TEMPLATE_{name_to_varname(display)}"
        dst     = os.path.join(CHAR_DIR, fname)
        shutil.copy2(src, dst)
        uid_map[uid] = (fname, varname)
        copied += 1

    print(f"已复制新模板: {copied} 个，缺失: {missing} 个")
    print(f"示例：106911 → {uid_map.get('106911', ('N/A', 'N/A'))}")

    # ── 3. 重写 assets.py ─────────────────────────────────────────────────────
    lines = [ASSETS_HEADER]

    # UNIT_NAMES dict（uid → 显示名）
    lines.append("# uid → 显示名（含星级），供 selector 使用\n")
    lines.append("UNIT_NAMES = {\n")
    for uid in valid_uids:
        if uid in uid_map:
            escaped = names[uid].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'    "{uid}": "{escaped}",\n')
    lines.append("}\n\n")

    # TEMPLATE_* 定义
    for uid in valid_uids:
        if uid not in uid_map:
            continue
        fname, varname = uid_map[uid]
        lines.append(
            f'{varname} = Template(file="./assets/character/{fname}")\n'
        )

    with open(ASSETS_PY, "w", encoding="utf-8") as f:
        f.writelines(lines)
    print(f"已重写 {ASSETS_PY}（{copied} 个 TEMPLATE + UNIT_NAMES）")


if __name__ == "__main__":
    main()
