"""
按钮提取工具
"""

import os, sys
import imageio
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(__file__)), "."))

from module.base.utils import get_bbox, get_color, image_size, load_image
from module.logger import logger

MODULE_FOLDER = "./module"
BUTTON_FILE = "assets.py"
IMPORT_EXP = """
from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.
"""
IMPORT_EXP = IMPORT_EXP.strip().split("\n") + [""]

# 资源文件夹路径
ASSETS_FOLDER = "./assets"


# ==================== ImageExtractor ====================


class ImageExtractor:
    """
    图像提取器 - 从截图中提取按钮定义
    """

    def __init__(self, module, file):
        """
        初始化图像提取器

        Args:
            module(str): 模块名称（如 'handler', 'login' 等）
            file(str): 文件名（如 'LOGIN_CHECK.png' 或 'LOGIN_CHECK.gif'）
        """
        self.module = module
        self.name, self.ext = os.path.splitext(file)
        self.area = None
        self.color = None
        self.button = None
        self.file = None
        self.load()

    def get_file(self, genre=""):
        """
        获取文件路径

        Args:
            genre(str): 文件类型（'', 'AREA', 'COLOR', 'BUTTON'）

        Returns:
            str: 文件路径
        """
        for ext in [".png", ".gif"]:
            file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
            file = os.path.join(ASSETS_FOLDER, self.module, file).replace("\\", "/")
            if os.path.exists(file):
                return file
        ext = ".png"
        file = f"{self.name}.{genre}{ext}" if genre else f"{self.name}{ext}"
        file = os.path.join(ASSETS_FOLDER, self.module, file).replace("\\", "/")
        return file

    def extract(self, file):
        """
        从文件中提取区域和颜色

        Args:
            file(str): 图像文件路径

        Returns:
            tuple: (bbox, mean_color)
        """
        if os.path.splitext(file)[1] == ".gif":
            # In a gif Button, use the first image.
            bbox = None
            mean = None
            for image in imageio.mimread(file):
                image = image[:, :, :3] if len(image.shape) == 3 else image
                new_bbox, new_mean = self._extract(image, file)
                if bbox is None:
                    bbox = new_bbox
                elif bbox != new_bbox:
                    logger.warning(
                        f"{file} has multiple different bbox, this will cause unexpected behaviour"
                    )
                if mean is None:
                    mean = new_mean
            return bbox, mean
        else:
            image = load_image(file)
            return self._extract(image, file)

    @staticmethod
    def _extract(image, file):
        """
        内部提取方法

        Args:
            image: 图像数组
            file: 文件路径

        Returns:
            tuple: (bbox, mean_color)
        """
        # 检查分辨率
        size = image_size(image)
        if size != (1280, 720):
            logger.warning(f"{file} has wrong resolution: {size}")

        # 获取边界框
        bbox = get_bbox(image)

        # 计算平均颜色并四舍五入
        mean = get_color(image=image, area=bbox)
        mean = tuple(np.rint(mean).astype(int))

        return bbox, mean

    def load(self):
        """
        加载按钮信息
        """
        file = self.get_file()
        if os.path.exists(file):
            # 提取基础信息
            area, color = self.extract(file)
            button = area

            # 检查 AREA 覆盖文件
            override = self.get_file("AREA")
            if os.path.exists(override):
                area, _ = self.extract(override)

            # 检查 COLOR 覆盖文件
            override = self.get_file("COLOR")
            if os.path.exists(override):
                _, color = self.extract(override)

            # 检查 BUTTON 覆盖文件
            override = self.get_file("BUTTON")
            if os.path.exists(override):
                button, _ = self.extract(override)

            self.area = area
            self.color = color
            self.button = button
            self.file = file
        else:
            # 文件不存在时记录错误
            logger.warning(f"{self.name} not found at {file}")
            self.area = None
            self.color = None
            self.button = None
            self.file = None

    @property
    def expression(self):
        """
        生成 Button 定义代码

        Returns:
            str: Python 代码字符串
        """
        return '%s = Button(area=%s, color=%s, button=%s, file="%s")' % (
            self.name,
            self.area,
            self.color,
            self.button,
            self.file,
        )


# ==================== TemplateExtractor ====================


class TemplateExtractor(ImageExtractor):
    """
    模板提取器 - 用于 TEMPLATE_ 开头的图片
    Template 只需要 file 参数，不需要 area/color/button
    """

    @staticmethod
    def extract(file):
        """
        提取模板信息（Template 实际上不需要提取，只需要文件路径）

        Args:
            file: 文件路径

        Returns:
            tuple: (bbox, mean_color)
        """
        image = load_image(file)
        bbox = get_bbox(image)
        mean = get_color(image=image, area=bbox)
        mean = tuple(np.rint(mean).astype(int))
        return bbox, mean

    @property
    def expression(self):
        """
        生成 Template 定义代码
        Template 只有 file 参数，不像 Button 有 area/color/button

        Returns:
            str: Python 代码字符串
        """
        return '%s = Template(file="%s")' % (self.name, self.file)


# ==================== ModuleExtractor ====================


class ModuleExtractor:
    """
    模块提取器 - 处理整个模块目录
    """

    def __init__(self, name):
        """
        初始化模块提取器

        Args:
            name(str): 模块名称（如 'handler'）
        """
        self.name = name
        self.folder = os.path.join(ASSETS_FOLDER, name)

    @staticmethod
    def split(file):
        """
        分割文件名

        Args:
            file(str): 文件名

        Returns:
            tuple: (name, sub, ext)
                例如: 'LOGIN_CHECK.AREA.png' -> ('LOGIN_CHECK', '.AREA', '.png')
        """
        name, ext = os.path.splitext(file)
        name, sub = os.path.splitext(name)
        return name, sub, ext

    def is_base_image(self, file):
        """
        判断是否为基础图像（非 .AREA/.COLOR/.BUTTON 等覆盖文件）

        Args:
            file(str): 文件名

        Returns:
            bool: 是否为基础图像
        """
        _, sub, _ = self.split(file)
        return sub == ""

    @property
    def expression(self):
        """
        生成模块的所有 Button 定义

        Returns:
            list: Python 代码行列表
        """
        exp = []

        for file in os.listdir(self.folder):
            # 跳过数字开头的文件
            if file[0].isdigit():
                continue

            # 处理 TEMPLATE_ 开头的文件
            if file.startswith("TEMPLATE_"):
                exp.append(TemplateExtractor(module=self.name, file=file).expression)
                continue

            # 处理基础图像文件
            if self.is_base_image(file):
                extractor = ImageExtractor(module=self.name, file=file)
                # 只添加成功提取的按钮
                if extractor.area is not None:
                    exp.append(extractor.expression)
                continue

        # 排序
        exp.sort()

        # 日志输出
        logger.info("Module: %s(%s)" % (self.name, len(exp)))

        # 添加导入语句
        exp = IMPORT_EXP + exp

        return exp

    def write(self):
        """
        将生成的代码写入文件

        生成文件位置: module/<module_name>/assets.py
        """
        # 确保目录存在
        folder = os.path.join(MODULE_FOLDER, self.name)
        if not os.path.exists(folder):
            os.mkdir(folder)

        # 写入文件
        with open(os.path.join(folder, BUTTON_FILE), "w", newline="") as f:
            for text in self.expression:
                f.write(text + "\n")


# ==================== Worker Function ====================


def worker(module):
    """
    工作函数 - 处理单个模块

    Args:
        module(str): 模块名称
    """
    me = ModuleExtractor(name=module)
    me.write()


# ==================== AssetExtractor ====================


class AssetExtractor:
    """
    资源提取器

    用法说明：

    1. 所有资源文件名应使用大写字母

    2. 数字开头的文件会被忽略
       例如: 2020XXXX.png

    3. TEMPLATE_ 开头的文件会被当作模板
       例如: TEMPLATE_AMBUSH_EVADE_SUCCESS.png
       生成: TEMPLATE_AMBUSH_EVADE_SUCCESS = Template(file='./assets/handler/TEMPLATE_AMBUSH_EVADE_SUCCESS.png')

    4. 其他文件会被当作按钮
       例如: GET_MISSION.png
       生成: Button(area=(553, 482, 727, 539), color=(93, 142, 203), button=(553, 482, 727, 539))

    5. XXX.AREA.png, XXX.COLOR.png, XXX.BUTTON.png 会覆盖 XXX.png 的对应属性
       例如: BATTLE_STATUS_S.BUTTON.png 覆盖 BATTLE_STATUS_S 的 'button' 属性
    """

    def __init__(self):
        """
        初始化并执行提取
        """
        logger.info("Assets extract")
        EXCLUDE_FOLDERS = ["mask"]

        modules = [
            m
            for m in os.listdir(ASSETS_FOLDER)
            if os.path.isdir(os.path.join(ASSETS_FOLDER, m))
            and m not in EXCLUDE_FOLDERS  # 排除特殊目录
        ]
        for module in modules:
            logger.hr(f"Processing module: {module}", level=2)
            worker(module)


# ==================== 主入口 ====================

if __name__ == "__main__":
    ae = AssetExtractor()
