import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Pcr'
    Scheduler_SuccessInterval = 0
    Scheduler_FailureInterval = 120
    Scheduler_ServerUpdate = '00:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_PackageName = 'auto'  # auto
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, DroidCast_raw, NemuIpc
    Emulator_ControlMethod = 'auto'  # auto, ADB, MaaTouch
    Emulator_AdbRestart = True

    # Group `Storage`
    Storage_Storage = {}
